version: '3.3'

services:

  sankey-api:
    image: grignon/sankey-api:v1
    ports:
      - "8080:80"
    networks:
      - sankey-net
  sankey-web:
    image: grignon/sankey-web:v1
    ports:
      - "8081:80"
    networks:
      - sankey-net    
  sankey-nginx:
    image: grignon/sankey-nginx:v1
    ports:
    - "80:80"
    depends_on:
      - sankey-api
      - sankey-web     
    networks:
      - sankey-net           

networks:
  sankey-net: